"""empty message

Revision ID: 1f75d99793ca
Revises: d248b4150bb2
Create Date: 2025-09-30 16:42:04.173015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f75d99793ca'
down_revision = 'd248b4150bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Books', schema=None) as batch_op:
        batch_op.drop_column('copies_available')
        batch_op.drop_column('copies_total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('copies_total', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('copies_available', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
