"""empty message

Revision ID: 20049f245130
Revises: 
Create Date: 2025-09-29 16:45:10.964822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20049f245130'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Books',
    sa.Column('isbn', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('copies_total', sa.Integer(), nullable=True),
    sa.Column('copies_available', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('isbn')
    )
    op.create_table('Copies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('due_back', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # drop dependent tables first
    op.drop_table('Copies')
    op.drop_table('Users')
    op.drop_table('Books')
    # ### end Alembic commands ###
