"""empty message

Revision ID: 205b858f805a
Revises: 97ca26b2fc6b
Create Date: 2025-09-30 11:14:04.091564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205b858f805a'
down_revision = '97ca26b2fc6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Books', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('Copies', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Copies', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('Books', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
