"""empty message

Revision ID: 6887fcd5bfa2
Revises: 1f75d99793ca
Create Date: 2025-10-03 11:52:14.413922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6887fcd5bfa2'
down_revision = '1f75d99793ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Books', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('Copies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Copies_isbn'), ['isbn'], unique=False)
        batch_op.create_index(batch_op.f('ix_Copies_username'), ['username'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_copy_username'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_book_isbn'), type_='foreignkey')
        batch_op.create_foreign_key('fk_copy_username', 'Users', ['username'], ['username'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_book_isbn', 'Books', ['isbn'], ['isbn'], ondelete='CASCADE')

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('Copies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_book_isbn', type_='foreignkey')
        batch_op.drop_constraint('fk_copy_username', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_book_isbn'), 'Books', ['isbn'], ['isbn'])
        batch_op.create_foreign_key(batch_op.f('fk_copy_username'), 'Users', ['username'], ['username'])
        batch_op.drop_index(batch_op.f('ix_Copies_username'))
        batch_op.drop_index(batch_op.f('ix_Copies_isbn'))

    with op.batch_alter_table('Books', schema=None) as batch_op:
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
