"""empty message

Revision ID: 8ab754eedd3b
Revises: 20049f245130
Create Date: 2025-09-29 17:01:36.064735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab754eedd3b'
down_revision = '20049f245130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Copies', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'Books', ['isbn'], ['isbn'])
        batch_op.create_foreign_key(None, 'Users', ['username'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Copies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('isbn',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
