"""empty message

Revision ID: 8ab754eedd3b
Revises: 20049f245130
Create Date: 2025-09-29 17:01:36.064735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab754eedd3b'
down_revision = '20049f245130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Copies', schema=None) as batch_op:
     batch_op.alter_column('isbn',
         existing_type=sa.String(),
         nullable=False)
     # use explicit names so Alembic can refer to them during downgrade
     batch_op.create_foreign_key('fk_book_isbn', 'Books', ['isbn'], ['isbn'])
     batch_op.create_foreign_key('fk_copy_username', 'Users', ['username'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Some databases / existing schemas may not have the named constraints
    # (they may have been created without an explicit name). Use
    # a safe IF EXISTS drop so downgrade doesn't fail when the constraint
    # is absent.
    op.execute('ALTER TABLE "Copies" DROP CONSTRAINT IF EXISTS fk_copy_username')
    op.execute('ALTER TABLE "Copies" DROP CONSTRAINT IF EXISTS fk_book_isbn')

    with op.batch_alter_table('Copies', schema=None) as batch_op:
     batch_op.alter_column('isbn',
         existing_type=sa.String(),
         nullable=True)

    # ### end Alembic commands ###
