"""empty message

Revision ID: 97ca26b2fc6b
Revises: c7ed62d39ae7
Create Date: 2025-09-30 11:06:59.569942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ca26b2fc6b'
down_revision = 'c7ed62d39ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Books', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('Copies', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Copies', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('Books', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
