"""empty message

Revision ID: c7ed62d39ae7
Revises: 8ab754eedd3b
Create Date: 2025-09-29 17:57:35.792310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ed62d39ae7'
down_revision = '8ab754eedd3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Books', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"Books_isbn_seq"\'::regclass)'))

    with op.batch_alter_table('Copies', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Copies', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('Books', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"Books_isbn_seq"\'::regclass)'))

    # ### end Alembic commands ###
