"""empty message

Revision ID: d248b4150bb2
Revises: 205b858f805a
Create Date: 2025-09-30 11:43:47.230897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd248b4150bb2'
down_revision = '205b858f805a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Books',
    sa.Column('isbn', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('copies_total', sa.Integer(), nullable=True),
    sa.Column('copies_available', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('isbn')
    )
    op.create_table('Users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('Copies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('due_back', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['Books.isbn'], name='fk_book_isbn'),
    sa.ForeignKeyConstraint(['username'], ['Users.username'], name='fk_copy_username'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Copies')
    op.drop_table('Users')
    op.drop_table('Books')
    # ### end Alembic commands ###
